// <auto-generated />
using System;
using DF.Ecommerce.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DF.Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(CarrinhoContext))]
    partial class CarrinhoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Carrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCupom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VlTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.HasIndex("IdCupom");

                    b.ToTable("tb_Carrinho");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tb_Cliente");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Cupom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("VlCupom")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("tb_Cupom");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.ItemCarrinho", b =>
                {
                    b.Property<Guid>("IdCarrinho")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("IdCarrinho", "IdProduto");

                    b.HasIndex("IdProduto");

                    b.ToTable("tb_ItemCarrinho");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("tb_Produto");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Carrinho", b =>
                {
                    b.HasOne("DF.Ecommerce.Domain.Entites.Cliente", "Cliente")
                        .WithOne("Carrinho")
                        .HasForeignKey("DF.Ecommerce.Domain.Entites.Carrinho", "IdCliente")
                        .IsRequired();

                    b.HasOne("DF.Ecommerce.Domain.Entites.Cupom", "Cupom")
                        .WithMany("Carrinhos")
                        .HasForeignKey("IdCupom")
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Cupom");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.ItemCarrinho", b =>
                {
                    b.HasOne("DF.Ecommerce.Domain.Entites.Carrinho", "Carrinho")
                        .WithMany("ItensCarrinhos")
                        .HasForeignKey("IdCarrinho")
                        .IsRequired();

                    b.HasOne("DF.Ecommerce.Domain.Entites.Produto", "Produto")
                        .WithMany("ItensCarrinhos")
                        .HasForeignKey("IdProduto")
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Carrinho", b =>
                {
                    b.Navigation("ItensCarrinhos");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Cliente", b =>
                {
                    b.Navigation("Carrinho");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Cupom", b =>
                {
                    b.Navigation("Carrinhos");
                });

            modelBuilder.Entity("DF.Ecommerce.Domain.Entites.Produto", b =>
                {
                    b.Navigation("ItensCarrinhos");
                });
#pragma warning restore 612, 618
        }
    }
}
